version: '3'

services:
  database:
    container_name: database-reservation
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=reservation
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_HOST_AUTH_METHOD=trust

    ports:
      - "5432:5432"
    volumes:
      - pgdata:/data/postgres

  backend:
    container_name: backend
    build: .
    restart: always
    ports: 
      - "3000:3000"
    depends_on:
      - database
    env_file:
      - .env

volumes:
  pgdata: 
    driver: local
