version: '3'

services:
  database:
    container_name: database-reservation
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=reservation
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_HOST_AUTH_METHOD=trust

    ports:
      - "5432:5432"
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata: 
    driver: local
